name: AIT-Project # Must match project customization repo name
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
      ## Uncomment for Deployment (Fetch from Repo)
      - git+https://github.com/NASA-AMMOS/AIT-Core.git
      - git+https://github.com/NASA-AMMOS/AIT-GUI.git
      
      ## Uncomment for Development (Prefer local clones made by make)
      # - ./AIT-Project
      # - ./AIT-Core
      # - ./AIT-GUI
variables:
  AIT_ROOT: ./AIT-Core
  AIT_CONFIG: ./AIT-Project/config/config.yaml