name: AIT_PROJECT # Must match project customization repo name
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    ## Prefer Remote
    - git+PROJECT_URL
    - git+AIT_CORE_URL
    - git+AIT_GUI_URL

    ## Prefer Local (Should local be default? Probably Yes)
    #- ./AIT_PROJECT 
    #- ./AIT-Core
    #- ./AIT-GUI
variables:
  AIT_ROOT: ./AIT-Core
  AIT_CONFIG: ./AIT_PROJECT/config/config.yaml