name: AIT-Project # Must match project customization repo name
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    # 
    - git+https://github.com/NASA-AMMOS/AIT-Core.git #Prefer Remote Repo
    - git+https://github.com/NASA-AMMOS/AIT-GUI.git      
    # - ./AIT-Project #Prefer Local Repo
    # - ./AIT-Core
    # - ./AIT-GUI
variables:
  AIT_ROOT: ./AIT-Core
  AIT_CONFIG: ./AIT-Project/config/config.yaml