# Run this makefile on the KMC Crypto Service server

kmc_server_setup:
	$(MAKE) -C ./server_config
	$(MAKE) -C ./crypto_service_config

clean:
	$(MAKE) -C ./server_config clean
	$(MAKE) -C ./crypto_service_config clean
